// 389. Find the Difference
// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

var findTheDifference = function(s, t) {

 let arr = [...t];
 let val;

  for(let i = 0 ; i<s.length; i++){
     for(let j = 0 ; i<arr.length; j++){
       if(s[i]==arr[j]){
        arr[j]=0
        break;
       }
  } 
  }

  for(let i=0;i<arr.length;i++){
    if(arr[i]!==0){
       val = arr[i];
    }
  }
  return val
}